- client/.gitignore
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Login/Login.component.js
- client/src/components/Login/index.js
- client/src/components/PrivateRoute/PrivateRoute.component.js
- client/src/components/PrivateRoute/index.js
- client/src/components/Profile/Profile.component.js
- client/src/components/Profile/index.js
- client/src/index.js
- client/src/pages/CheeseDetail/index.js
- client/src/react-auth0-spa.js
- client/src/serviceWorker.js
- client/src/utils/API.js
- package-lock.json
- package.json
- routes/index.js
* Button for login/logout
* Profile route/component
* (Functions needed for handling both above live in react-auth-spa.js if you're interested)
* NPM dependencies (should install what Auth0 needs automagically per our fancy scripts but hit me up if not)
* See slack for config file with necessary domain and clientId keys that won't be shared on git but needed to run on your machine, please do not share these and make sure your .gitignore contains 'auth_config.json'
* The "cheese stuff" is from Wednesday's class, it will be nice to have this up and running for when we move to populate our API.
> Auth0 coming in hot!

- client/src/components/Login/Login.component.js
- client/src/components/Profile/Profile.component.js
- client/src/components/User/User.component.js
- client/src/components/User/index.js
- client/src/pages/PlantDetail/PlantDetail.component.js
- client/src/pages/Plants/Plants.component.js
- client/src/react-auth0-spa.js
Created a User component that display the current user's unique google ID, we will use this to query the db to find a specific user's plants.
I just wanted to create this so we could reference the correct information while working and testing the app.  We can change this to pull our user's email instead if we would rather use that as a unique identifier, it's easy enough to rewrite the Auth0 code to spit out what we want.
> Auth0 User Component (just used in testing)

- client/package-lock.json
- client/src/App.js
- client/src/components/Login/Login.component.js
- client/src/components/Profile/Profile.component.js
- client/src/pages/Dashboard/index.js
- client/src/pages/Landing/Landing.component.js
- client/src/pages/Landing/index.js
Added `Landing.component` in `/pages` that now contains the `Login` functionality.  Also added the component to the `/` route in `App.js`.  `/dashboard` now contains the `Login` component which naturally displays `Logout` instead.
p.s. I believe this PR will contain my other recent PR to the Auth0 branch because I built this LandingPage branch from the Auth0 branch before it was merged to master.  Sorry, I hope there isn't a problem but if there are any concerns or merge conflicts I'll work to resolve them with you.  LMK.
> Landing page

- client/src/components/ImgThumbnail/index.js
> ImgThumbnail component created

- client/src/components/ImgThumbnail/index.js
- client/src/components/PlantNameDisplay/index.js
- client/src/components/PlantNameDisplay/styles.css
Resolves #21 
Styles.css has a placeholder for the Comfortaa font for now until we officially import the CDN into our project.
> Plant name display

- client/package-lock.json
- client/src/components/InfoCard/index.js
- client/src/pages/PlantDetail/PlantDetail.component.js
Initial Set up of the Info Card that will live on the plant detail page
> Info Card setup for plant detail page

- client/package-lock.json
- client/src/components/Button/index.js
Simple button component, contains props for naming and onClick so we can change the use case depending on what is needed for the `page` the button is imported on.
Resolves #14
> Button component

- client/src/components/Header/index.js
Header component for survey page or other use.
Not much going on here until we style it on the page but there she is!
Resolves #15
> Header component

- client/src/components/QACards/index.js
Question/Answer Cards components, set up to have data mapped into them via props.
Unique ids will be created for each card corresponding to the question number when mapped.
Resolves #16
> QA Card component

- client/src/pages/Survey/Plants.json
- Added plants to plants.json file. 
- Total of 15 plants now available. 
- Removed hardiness zones 
- Added nontoxic data
> Added plants to plants.json file. 

- client/src/components/PlantDisplayCard/index.js
- client/src/components/PlantDisplayCard/styles.css
Stole this component from my google-react-books assignment. I used reactstrap for it which is why there are already component imports in the file. If we choose to use the boostrap cdn instead I can always change these to reflect that.
> Created PlantDisplayCard component

- client/package-lock.json
- client/public/index.html
- client/src/components/PlantDisplayCard/index.js
- client/src/components/PlantDisplayCard/styles.css
- client/src/index.css
- client/src/pages/Dashboard/index.js
Enhanced the look of our Dashboard page by doing the following: 
- Imported reactstrap components Container, Row, and Col to Dashboard Page Component
- Organized the Dashboard Page Component by rows and columns. 
- Added necessary components that will display such as the Plant Display Card and Nav bar (though Nav bar is not currently displaying, see @jnieves14 )
- Added more css styling to index.css to reflect in Dashboard Page 
- In PlantDisplayCard component, I have added in an image (temporarily replacing props.image) just so we can see how it will look. Once we pull in data this is to be replaced. 
- In PlantDisplayCard component, added div "plant-info" with text that will be replaced with props retrieving user plant data. 
- In PlantDisplayCard component, commented OUT the button - …
> Dashboard Styling

- client/src/pages/Survey/Plants.json
I have added the following to the plants array:
- Water description
- Weeks (tells us amount of weeks between waterings)
- Days (tells us amount of days between waterings - figured this may be a useful number depending on what calendar we use)
- Plant Bio - gives a quick blurb about the plant from a 1st person perspective to help give the user a more personal tie to the plant they are about to pick and help educate them a bit more about what plant they may want to choose.
> Added more fields to Plants.JSON File

- bin/www
- controllers/plantsController.js
- models/index.js
- models/plant.js
> Added mongoDB schema and starter code for controller

- client/src/components/BottomNavigation/index.js
- client/src/components/Login/Login.component.js
- client/src/index.css
- client/src/pages/Dashboard/index.js
Edited the nav bar's 
- colors
- fixed the position
- fixed the height of the icons
- removed the labels so that when page is active, there is no text appearing underneath the icon of the active page
> Styled nav bar

- client/package-lock.json
- client/src/pages/Survey/Plants.json
- client/src/pages/Survey/Questions.json
Added plant scores to plants.json file
Changed some answers in QAjson file
> plant scores and some QA answers changed

- client/src/components/BottomNavigation/index.js
- client/src/components/Login/Login.component.js
- Added logout icon in bottom nav bar
- is functional
- issue: logout button is currently in two places at once - will fix later
> Added a Logout ICON in bottom nav bar

- client/src/components/BottomNavigation/index.js
- client/src/components/Login/Login.component.js
- client/src/components/WateringSchedule/index.js
- client/src/pages/PlantDetail/PlantDetail.component.js
- package-lock.json
- package.json
- Installed react-moment npm package 
- used react-moment in new 'WateringSchedule' component to retrieve today's date and add to it any number of days based on watering frequency of plant
**Dependencies:** Waiting on MongoDB to make query for watering frequency from users plants to be able to add it to the logic 
IF more time allows: 
- next step is to allow user to select how long ago they watered their plant and allow react-moment to make the appropriate calculation for when to water next 
- next step after the one above (if time allows) is to use the Google Calendar API to post to their calendar. After doing research this seemed time intensive along with other complications. Will discuss in person. 
OTHER ITEMS WORKED ON:
- removed double log-out button by moving the 'logout' logic …
> Added Watering Schedule (MVP only)

- package-lock.json
- package.json
- routes/api/index.js
- routes/api/plants.js
- routes/index.js
here are the routes we have so far:
- GET /api/plants (grabs all plants in db, still need to implement filtering by user id but this is enough to start with for now)
- POST /api/plants (posts a plant to the DB)
- DELETE /api/plants/:id (deletes a plant by a specific id)
- I still need to implement a get plant by specific id, but this should be enough to work with for now.
> preliminary API routes implemented

- client/src/pages/Results/index.js
- client/src/utils/API.js
- models/plant.js
Added on click handler for add plant button that saves plants to db. I didn't remember how to pull in the Auth0 user id so right now the userID is being populated with a placeholder value. @Bigshmow if you can help me with this I can close out issue #57.
> Plant button logic

- client/src/components/User/User.component.js
- client/src/pages/Dashboard/index.js
- client/src/pages/Results/index.js
userId aka googleAuth0 identifier saved to local storage upon log in, added userId to savePlant Axios
> UserId is set to local storage

- client/src/components/PlantDisplayCard/index.js
- client/src/pages/Dashboard/index.js
- client/src/pages/Results/index.js
- client/src/utils/API.js
- controllers/plantsController.js
- routes/api/plants.js
Resolves issue #54. Also fixed a minor issue where About Me would render in dashboard; it will now only conditionally render in the Results page.
Also started on issue #58, clicking on the details button in the dashboard will take you to the plants detail page and the plant ID gets passed to the new page.
Will start a new branch to actually populate plant info from the db in the details page.
> Dashboard card

- client/package-lock.json
- client/src/pages/Dashboard/index.js
I added a condition to comp did update to prevent constant pinging of the server.
Also added a key to the plantcard component.
> App constantly pinging the server

- client/src/components/BottomNavigation/index.js
- client/src/index.css
Was running into issues with the icons in the Navigation Bar displaying properly with the logout button - made some changes to the way it's being handled in JSX in the component.
Styling now needs to be done to it in the global css. Pushing this file up now so I can pull down because I am behind. Once merged, I will work on CSS to get this nav bar looking right. 
Please test the navbar buttons (logout, login) to make sure it still works.
> Navbar Component Changes

- client/package-lock.json
- client/src/components/InfoCard/index.js
- client/src/pages/Dashboard/index.js
- client/src/pages/PlantDetail/PlantDetail.component.js
- client/src/utils/API.js
- models/plant.js
Resolves issue #58. 
Plant detail page will still need to be styled but it at least will now pull data from the db when you navigate to plant details from the dashboard.
> Plant detail

- client/src/components/BottomNavigation/index.js
- client/src/pages/Dashboard/index.js
added onclicks to the navbar buttons to load a new window.
also included in this PR is a simple change to strict equals when dashboard loads in plants, as well as unused imports being removed.  should squawk at us less now.
> Navbar links

- client/src/components/Button/index.js
- client/src/components/QACards/index.js
- client/src/index.css
- client/src/pages/Survey/Survey.component.js
Made CSS Fixes to the Survey Page. Fixes allow for:
- More room at bottom so user can now see the submit button
- Adjusted the font sizing and font family of the questions
- Changed the Submit button's color and centered to page
> Survey Page CSS Style Fixes & Submit Button CSS Fixes

- client/src/index.css
- client/src/pages/Dashboard/index.js
**Adjusted the Bottom Navigation Bar CSS.**
Fixes: 
- Displays center 
- icons evenly spaced out
> Navigation Bar CSS Fix

- client/src/pages/PlantDetail/PlantDetail.component.js
- client/src/pages/PlantDetail/style.css
Pulled in the plant image for the Plant Detail Page
> Plant Detail Page - Image Added

- models/plant.js
This prevented adding more than one plant at a time
> Fixed userID bug in db model 

- client/src/components/WateringSchedule/index.js
- client/src/pages/PlantDetail/PlantDetail.component.js
- client/src/pages/Results/index.js
- models/plant.js
createdAt date and lastWatering Date added
> createdAt date and lastWatering Date added

- client/src/components/WateringSchedule/index.js
Added dates from Database into WateringSchedule component to show accurate watering times to user.
The user will now see in how many days they need to water their plant based on when they added the plant. 
The user will also see a note if they have not watered their plant on time to water their plant today 
Future Changes: 
- I will add "last watered" plant date to the formula as well so users can say when they last watered it and it will give the "water in X days" more accurate
> Watering Schedule Component Adjustments

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/config.js
- client/src/pages/Feed/Feed.component.js
- package-lock.json
- package.json
Visit "localhost:3000/feed" to begin
Click the `Add your plant pic!` button and perform the familiar file upload process:
The image is displayed using the downloadURLs now contained in state.
These images are being stored on firebase in order to create the host URL.
**note: you may have to npm i --save firebase && react-firebase-file-uploader in the /client**
**You will need to update the .env folder with the slacked vars**
> Feed Class

- client/src/pages/PlantDetail/PlantDetail.component.js
Set up the Plant Detail Page Component for accepting today's date as the Last Watered Date. I added a pencil icon next to the "water in __ days". 
Currently the pencil button works to retrieve todays date and set state to change last watered date in database. Peter helped me add 'lastWatered' in the models so there is a field in the object to accept a last watered date. 
**Next Steps:** 
- I believe I need to connect to the API to update the lastWatered  database? 
- need to add if/else to water component that will include the last watered date as a part of the logic. (if lastWatered = null, then assume plant added date is the last watered date, until user checks off that they watered the plant, then update lastWatered)
> Water Edit Icon + lastWatered entry for database

- client/src/pages/Feed/Feed.component.js
- controllers/feedController.js
- models/feed.js
fixed some typos in feed model and feed controller
social posts, img download url now saving to a new collection called feed.
data is now being pulled from db and sorted on component mount.
> Typos and feed class updates

- client/src/components/BottomNavigation/index.js
- client/src/index.css
feed icon added added to bottom navigation for now
> feed icon and path added to bottom navigation

- client/src/components/BottomNavigation/index.js
- client/src/components/PlantDisplayCard/index.js
- client/src/index.css
changed plantDisplayCard component so that the plant's nickname will only be displayed on plant cards that were added through the add plant page/option
> Nickname option

- client/src/pages/AddPlant/AddPlant.component.js
imported and displayed
passed to state
> Addplantpic

- client/src/pages/Results/index.js
User is now alerted when they add a plant
> Results class alert on add

- client/src/components/InfoCard/index.js
- client/src/components/PlantDisplayCard/index.js
- client/src/pages/AddPlant/AddPlant.component.js
- client/src/pages/PlantDetail/PlantDetail.component.js
Okey dokey! Not too sure how we want water care information displayed and we can talk more on Monday, but I made it an option to have all water care instructions displayed.
Also, added a delete button to the plant detail page that will delete that plant and redirect you back to the dashboard.
> Water care and delete

- client/package-lock.json
- client/src/components/PlantDisplayCard/index.js
- client/src/components/PlantDisplayCard/styles.css
- client/src/index.css
- client/src/pages/Dashboard/index.js
- client/src/pages/Results/index.js
- Header text now white
- plant cards now full width of screen - border removed with new bottom border added for cleanliness
- Edited margin in nav bar icons to make then more even now that we have an extra icon
> Small CSS Fixes: Header Text, Nav Bar Spacing, Plant Cards

- client/public/index.html
body now has a background color, using white for now.
hopefully this fixes the awful black bg in heroku.  It changes my local bg color so chances are this is all we need to implement.
> <Body> now has bg color

- client/src/pages/PlantDetail/PlantDetail.component.js
MongoDB now receives lastWatered time when user marks that they have watered plant
> lastWatered API call functional

- client/src/index.css
- client/src/pages/AddPlant/AddPlant.component.js
- client/src/pages/AddPlant/AddPlant.css
- client/src/pages/PlantDetail/PlantDetail.component.js
- The scrolling issue should be fixed now on the Plant Detail and Add Plant Pages. 
- In Plant Detail - I put the "water in _ days" into a card for a cleaner look. 
- I replaced the pencil icon with a water icon - the user clicks it and the following happens: - lastWatered Date is updated, the icon turns blue, an alert pops up saying "Plant Watered!"
> Scrolling Fixed, Watering Schedule Card Adjustments

- client/src/components/PlantDashCard/index.js
- client/src/index.css
- client/src/pages/Dashboard/index.js
My dashboard kept getting cut off at the bottom when I had too many plants. 
I thought I fixed this earlier, but hopefully this finally fixes it. 
Wrapped the entire PlantDashCard in a div and it seems to be cooperating now.
> Dashboard scroll fix

- client/src/index.css
- client/src/pages/Dashboard/index.js
- client/src/pages/Results/index.js
replaced bottom border with <hr> for division of plants - 
Please test on your device to make sure it is not breaking like the bottom border was
> Plant Card Divider Replacement

- client/src/pages/Results/Plants.json
The plants `JSON` was not consistent so I just chose to add periods to all of the bios rather than omit them.
> Grammar mostly just adding periods

- client/src/components/WateringSchedule/index.js
- client/src/pages/PlantDetail/PlantDetail.component.js
water ternary added that will say "water tomorrow" if watering day is in 1 day
> watering ternary

- client/src/components/PlantDashCard/index.js
- client/src/index.css
The dashboard plant cards are now in rows and columns for organization - 
the plant name is now in a gray background 
- still more fixes to come
> dashboard card styling

- client/src/pages/Feed/Feed.component.js
Added button images (instead of text).
Using reactstrap `CardColumns` component formatted page to be super nice.
> Format and style feed page

- client/src/components/PlantDashCard/index.js
- client/src/components/WateringSchedule/index.js
- client/src/pages/Dashboard/index.js
watering schedule in dashboard now working
> watering schedule in dashboard now working

- client/src/components/PlantDashCard/index.js
- client/src/components/WateringSchedule/index.js
- client/src/index.css
Small fixes - I am still super unhappy with how the dashboard plant cards look, but to fix it would mean a complete overhaul - Will discuss with team on video chat tonight.
> small fixes to dashboard plant name boxes

- client/src/components/BottomNavigation/index.js
Using the`<BottomNavigationAction />` to change routes instead of custom onClick handlers and window.location change.
> BottomNavigation update

- client/src/components/PlantDashCard/index.js
- client/src/components/WateringSchedule/index.js
- client/src/index.css
- client/src/pages/Dashboard/index.js
- Removed the Card / CardBody / CardText from the PlantDashCard to remove the unwanted library styling 
- added responsiveness to images to make them appear bigger after a certain screen size 
- Plant Header Text is now fixed (doesn't appear extra tiny on a bigger device)
- Is now centered properly 
- font for 'water again in _ days" gets bigger on iPad / Desktop 
- Plant Card now gets put into a card with a border for iPad / Desktop
- In iPad or Desktop view, the Plant Title text will get bigger and the gray background for it will disappear for a cleaner look 
MORE TO COME: 
- would like to make page even more responsive to desktop, will continue working on this.
> Dashboard Desktop CSS Changes

- client/src/components/InfoCard/index.js
- client/src/components/PlantDisplayCard/index.js
- client/src/index.css
Changes to make desktop more responsive and aesthetically-pleasing led to breaking of display of "Care Info" text & Results Page Images 
This commit will fix those 2 issues
> Bug Fix - "Care Info" Text on Plant Detail Page & Results Page Img Fix

- client/src/components/InfoCard/index.js
- client/src/components/PlantDisplayCard/index.js
- client/src/index.css
Buttons now look the same everywhere- the purple with rounded borders and same font.
> buttons now all consistent across the site
